namespace: global-movers-prod
environment: prod

app:
  image:
    tag: latest # Production release
  replicas: 2  # Higher availability in prod

ingress:
  host: global-movers.local  # Production domain
